CognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: TasksUserPool-${self:provider.stage}
    UsernameAttributes:
      - email

CognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    UserPoolId: !Ref: CognitoUserPool
    ClientName: TasksUserPoolClient-${self:provider.stage}
    AllowOAuthFlowsUserPoolClient: true
    AllowedOAuthScopes:
      - email
      - openid
      - profile
    SupportedIdentityProviders:
      - COGNITO
    AllowedOAuthFlows:
      - implicit
      CallbackURLs:
      - http://localhost:3000
      DefaultRedirectURI: http://localhost:3000

CognitoUserPoolDomain:
  Type: AWS::Cognito::UserPoolDomain
  Properties:
    Domain: tasksauthidp-${self:provider.stage}
    UserPoolId: !Ref: CognitoUserPool
